repo-name = bit-os
masters = gentoo
auto-sync = true
thin-manifests = true
sign-manifests = true
cache-formats = md5-cache
manifest-hashes = BLAKE2B SHA512
eapis-deprecated = 0 1 2 3 4 5 6
eapis-banned = 0 1 2 3 4 5 6